/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import Logica.FachadaServicios;
import Logica.observer.Observable;
import Logica.observer.Observer;
import controlador.DialogoMozoTransferirMesaControlador;
import dominio.Mesa;
import dominio.Mozo;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author yamil
 */
public class DialogoMozoTransferirMesa extends javax.swing.JDialog implements DialogoMozoTransferirMesaVista{
    
    private DialogoMozoTransferirMesaControlador controlador;
    
    /**
     * Creates new form DialogoMozosConectados
     */
    public DialogoMozoTransferirMesa(java.awt.Frame parent, boolean modal, Mozo mozo, Mesa mesa) {
        super(parent, modal);
        initComponents();
        this.controlador= new DialogoMozoTransferirMesaControlador(this, mozo, mesa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listMozosConectados = new javax.swing.JList();
        lblListMozosConectados = new javax.swing.JLabel();
        lblTransfiriendoMesa = new javax.swing.JLabel();
        btnTransferirMesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(listMozosConectados);

        lblListMozosConectados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblListMozosConectados.setText("Seleccione un mozo");

        lblTransfiriendoMesa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTransfiriendoMesa.setText("Transfiriendo mesa ");

        btnTransferirMesa.setText("Transferir");
        btnTransferirMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTransfiriendoMesa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblListMozosConectados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTransferirMesa)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTransfiriendoMesa)
                .addGap(18, 18, 18)
                .addComponent(lblListMozosConectados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTransferirMesa)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferirMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirMesaActionPerformed
        System.out.println("click");
        transferirMesa();
    }//GEN-LAST:event_btnTransferirMesaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferirMesa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListMozosConectados;
    private javax.swing.JLabel lblTransfiriendoMesa;
    private javax.swing.JList listMozosConectados;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cerrarVista() {
       this.dispose();
    }

    @Override
    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje,"Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void cargarMozosConectados(ArrayList<Mozo> mozosConectados) {
        listMozosConectados.setListData(mozosConectados.toArray());
    }

    public void setLabelInicio(String texto){
        lblTransfiriendoMesa.setText(texto);
    }
    
    private void transferirMesa(){
        Mozo mozoSeleccionado= (Mozo) listMozosConectados.getSelectedValue();
        System.out.println("MOZO "+mozoSeleccionado);
        controlador.transferirMesa(mozoSeleccionado);
    }

}
